spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hanspace
    hikari:
      password: 1234
      username: root
      driver-class-name: com.h2.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'